[profile.default]
src = 'src' # could be change for hardhat as well
out = 'out'
libs = ['lib'] #where are our libs
# remappings = ['']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
